### ISSUE TITLE
This package is not working, I get these errors on startup

### ISSUE THREAD

**Issue by zaid03** [degouville/atom-bootstrap4#38]
<img width="1280" alt="screen shot 2018-08-07 at 8 54 02 pm" src="https://user-images.githubusercontent.com/36865126/43790579-0b6bdf96-9a84-11e8-9517-a5408598061c.png">

**Comment by emileond** [comment]
Same here

**Comment by shynline** [comment]
same

**Comment by fdq09eca** [comment]
same here.

**Comment by JRudransh** [comment]
## See issue #26, There i posted the solution.
##### If you faced any other problem DM me on Twitter [JRudransh](https://twitter.com/JRudransh)
