### ISSUE TITLE
Failed to load snippets.

### ISSUE THREAD

**Issue by jade28** [degouville/atom-bootstrap4#41]
I have some problems with atom-bootstrap4.
How to fix it, thank you so much!
![screenshot from 2018-10-03 21-56-02](https://user-images.githubusercontent.com/34389409/46419096-552e9b00-c757-11e8-9c19-c30e426fc78f.png)

**Comment by ArthurMarjanovic** [comment]
https://github.com/degouville/atom-bootstrap4/issues/25#issuecomment-377848555
