### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by samsamm777** [degouville/atom-bootstrap4#9]
typing any of the shortcuts and pressing tab does nothing. the autocomplete menu has my word in it, but its not swapped for the code snippet.

**Comment by ironcove** [comment]
Agree...the short cuts do not work. Love the idea but can't get this to work.

**Comment by degouville** [comment]
"Doesn't look like anything to me." 👨‍💻

Which version are you using?
And which shortcut is broked ? 

___
Work fine on **V1.12.7** w/ a clean Atom install.

**Comment by ironcove** [comment]
I will reinstall and do a clean install. Pissed as I want this to work. I built my site on bootstrap and love how fast atom is and what you built.


Patrick Monahan
President/CEO
Office: 213.545.0601<tel:310.823.2047%20ext%201010>
Patrick@ironcovesolutions.com<mailto:Patrick@ironcovesolutions.com>

**Comment by degouville** [comment]
@ironcove after that, please give me a feedback... 😉

**Comment by AsgerMathiasen** [comment]
My tab does not work, how can i bind it to another key?

**Comment by namnh06** [comment]
I don't know how to use it

**Comment by jennaprice** [comment]
It will not work if you have emmet installed an enabled. That is why mine didn't work.

**Comment by rayggr** [comment]
@namnh06  Did you figure it out how to use it? I have the same problem as well.

**Comment by namnh06** [comment]
@rayggr switch to VS Code already bro :)).

**Comment by Rashidkhann** [comment]
wow its now working after disable/uninstalling emmet package and then restart atom it will work now
thanks to jennaprice  :)

**Comment by alueckenhoff-uta** [comment]
Is there another package that might be interfering. Having the same problem, but don't have emmet installed
